#%RAML 1.0 Library
types:
  ContactInformation:
    description: A generic and expandable key-value-store for adding present and future ContactInformation-attributes to any information object.
    type: object

    properties:
      contactInformationType:
        type: string
        description: The type (key) of the ContactInformation-attribute.
        displayName: Contact information type
        enum:
          - PHONE
          - EMAIL
          - NAME
      value:
        type: string
        description: One value for this contactInformationType.
        displayName: Value
