#%RAML 1.0 Library

types:
  ContactInformation:
    description: Contact information for a person

    properties:
      phone:
        type: string
        description: phone number of the person
        displayName: phone number

      email:
        type: string
        description: the email adress of the person
        displayName: email adress

      name:
        type: string
        description: the full name of the person
        displayName: full name