#%RAML 1.0 Library
uses:
  Link: ./annotation/Link.raml
  IdentifiableArtefact: ./abstract/IdentifiableArtefact.raml
  MultilingualText: ./abstract/MultilingualText.raml
  AdministrativeDetails: ./abstract/AdministrativeDetails.raml
  ContactInformation: ./abstract/ContactInformation.raml
  ClassificationSubsetCode: ./abstract/ClassificationSubsetCode.raml

types:
  ClassificationSubsetVersion:
    description: A subset of classifications
    displayName: Classification subset version
    type: [ IdentifiableArtefact.IdentifiableArtefact ]

    properties:
      versionId:
        type: string
        description: unique id of this version of this subset
        displayName: Version ID

      subsetId:
        type: string
        description: The global unique identifier (GUID) of the subset series this version belongs to
        displayName: Subset ID

      administrativeStatus:
        type: string
        description: Indicator for access to an item.
        displayName: Administrative status
        enum:
          - DRAFT
          - OPEN

      versionRationale?:
        type: MultilingualText.MultilingualText[]
        description: The reason for making this version of the information object.
        displayName: Version rationale

      lastModified:
        type: datetime
        description: The date on which the object was last updated.
        displayName: Last modified date time

      lastModifiedBy?:
        type: ContactInformation.ContactInformation[]
        description: Last updated by
        displayName: Last updated by

      validUntil?:
        type: datetime
        description: The date on which the information object is no longer effective or valid.
        displayName: Valid until

      codes:
        type: ClassificationSubsetCode.ClassificationSubsetCode[]
        description: A list of references to classification items
        displayName: Codes