#%RAML 1.0 Library
uses:
  Link: ./annotation/Link.raml
  IdentifiableArtefact: ./abstract/IdentifiableArtefact.raml
  MultilingualText: ./abstract/MultilingualText.raml
  AdministrativeDetails: ./abstract/AdministrativeDetails.raml
  ContactInformation: ./abstract/ContactInformation.raml
  ClassificationSubsetVersion: ./ClassificationSubsetVersion.raml

types:
  ClassificationSubsetSeries:
    description: A subset of classifications
    displayName: Classification subset series
    type: [ IdentifiableArtefact.IdentifiableArtefact ]

    properties:
      classificationType?:
        type: string
        description: What kind of classificaiton this is (Always Subset if present)
        displayName: Kind of classification

      owningSection:
        type: string
        description: Statistics Norway Division responsible for the subset updates.
        displayName: Owning section

      statisticalUnits?:
        type: string[]
        description: Statistical unit references a subset tagged with.
        displayName: Staistical units

      versions:
        type: string[]
        description: Versions of the classification code set for different validity periods.
        displayName: Versions
        (Link.types): [ ClassificationSubsetVersion ]

      versionRationale?:
        type: MultilingualText.MultilingualText[]
        description: The reason for making this version of the information object.
        displayName: Version rationale

      lastModified:
        type: datetime
        description: The date on which the object was last updated.
        displayName: Last modified date time

      lastModifiedBy?:
        type: ContactInformation.ContactInformation[]
        description: Last updated by
        displayName: Last updated by

      administrativeDetails?:
        type: AdministrativeDetails.AdministrativeDetails[]
        description: Administrative details (e.g. default language, documentation, localID, ...).
        displayName: Administrative details
