#%RAML 1.0 Library
uses:
  Link: ./annotation/Link.raml
  Domain: ./abstract/Domain.raml
  MultilingualText: ./abstract/MultilingualText.raml
  AdministrativeDetails: ./abstract/AdministrativeDetails.raml
  AgentDetails: ./abstract/AgentDetails.raml
  ClassificationSubsetCode: ./abstract/ClassificationSubsetCode.raml
  AgentInRole: ./AgentInRole.raml

types:
  ClassificationSubsetVersion:
    description: A subset of classifications
    displayName: Classification subset
    type: Domain.Domain

    properties:
      versionId:
        type: string
        description: unique id of this version of this subset
        displayName: Version ID

      subsetId:
        type: string
        description: The global unique identifier (GUID) of the subset series this version belongs to
        displayName: Subset ID

      description?:
        type: MultilingualText.MultilingualText[]
        description: The description of the information object
        displayName: Description

      shortName?:
        type: string
        description: A short technical name. (Avoid special characters not supported as variable names in common programming languages).
        displayName: Short name

      administrativeStatus:
        type: string
        description: Indicator for access to an item.
        displayName: Administrative status
        enum:
          - DRAFT
          - INTERNAL
          - OPEN
          - DEPRECATED

      statisticalUnits?:
        type: string[]
        description: Statistical unit references a subset tagged with.
        displayName: Staistical units
        #TODO: link to statisticalUnit (id/guid)?

      createdDate:
        type: date-only
        description: The date on which the information object was created
        displayName: Created date

      versionRationale?:
        type: MultilingualText.MultilingualText[]
        description: The reason for making this version of the information object.
        displayName: Version rationale

      lastModified:
        type: datetime
        description: The date time on which the object was last updated.
        displayName: Last modified date time

      lastModifiedBy?:
        type: AgentDetails.AgentDetails[]
        description: Last modified by
        displayName: Last modified by

      validFrom:
        type: date-only
        description: The date on which the information object is effective or valid. Set this date only once (constant). The same date for all versions of this information object.
        displayName: Valid from

      validUntil?:
        type: date-only
        description: The date on which the information object is no longer effective or valid.
        displayName: Valid until

      administrativeDetails?:
        type: AdministrativeDetails.AdministrativeDetails[]
        description: Administrative details (e.g. default language, documentation, localID, ...).
        displayName: Administrative details

      codes:
        type: ClassificationSubsetCode.ClassificationSubsetCode[]
        description: A list of references to classification items
        displayName: Codes