#%RAML 1.0 Library
uses:
  Link: ./annotation/Link.raml
  MultilingualText: ./abstract/MultilingualText.raml
  AdministrativeDetails: ./abstract/AdministrativeDetails.raml
  ContactInformation: ./abstract/ContactInformation.raml
  ClassificationSubsetVersion: ./ClassificationSubsetVersion.raml

types:
  ClassificationSubsetSeries:
    description: A subset of classifications
    displayName: Classification subset series
    type: object

    properties:
      classificationType?:
        type: string
        description: What kind of classificaiton this is (Always Subset if present)
        displayName: Kind of classification

      id:
        type: string
        description: The global unique identifier (GUID) of the information object assigned by the owner agency.
        displayName: Id

      name:
        type: MultilingualText.MultilingualText[]
        description: A term which designates a concept, in this case an information object. The identifying name will be the preferred designation. There will be many terms to designate the same information object, such as synonyms and terms in other languages.
        displayName: Name

      description?:
        type: MultilingualText.MultilingualText[]
        description: The description of the information object
        displayName: Description

      shortName?:
        type: string
        description: A short technical name (Avoid special characters not supported as variable names in common programming languages).
        displayName: Short name

      createdDate:
        type: datetime
        description: The date on which the information object was created
        displayName: Created date

      owningSection:
        type: string
        description: Statistics Norway Division responsible for the subset updates.
        displayName: Owning section
        #TODO: link to Division (id/guid)?

      statisticalUnits?:
        type: string[]
        description: Statistical unit references a subset tagged with.
        displayName: Staistical units
        #TODO: link to statisticalUnit (id/guid)?

      versions:
        type: string[]
        description: Versions of the classification code set for different validity periods.
        displayName: Versions
        (Link.types): [ ClassificationSubsetVersion ]

      versionRationale?:
        type: MultilingualText.MultilingualText[]
        description: The reason for making this version of the information object.
        displayName: Version rationale

      lastModified:
        type: datetime
        description: The date on which the object was last updated.
        displayName: Last modified date time

      lastModifiedBy?:
        type: ContactInformation.ContactInformation[]
        description: Last updated by
        displayName: Last updated by

      contactPerson?:
        type: ContactInformation.ContactInformation[]
        description: Contact info to the person responsible for this subset
        displayName: Contact information

      administrativeDetails?:
        type: AdministrativeDetails.AdministrativeDetails[]
        description: Administrative details (e.g. default language, documentation, localID, ...).
        displayName: Administrative details