#%RAML 1.0 Library
uses:
  Link: ./annotation/Link.raml
  MultilingualText: ./abstract/MultilingualText.raml
  AdministrativeDetails: ./abstract/AdministrativeDetails.raml
  ContactInformation: ./abstract/ContactInformation.raml
  ClassificationSubsetCode: ./abstract/ClassificationSubsetCode.raml
  AgentInRole: ./AgentInRole.raml

types:
  ClassificationSubsetVersion:
    description: A subset of classifications
    displayName: Classification subset
    type: object

    properties:
      versionId:
        type: string
        description: unique id of this version of this subset
        displayName: Version ID

      subsetId:
        type: string
        description: The global unique identifier (GUID) of the subset series this version belongs to
        displayName: Subset ID

      name:
        type: MultilingualText.MultilingualText[]
        description: A term which designates a concept, in this case an information object. The identifying name will be the preferred designation. There will be many terms to designate the same information object, such as synonyms and terms in other languages.
        displayName: Name

      description?:
        type: MultilingualText.MultilingualText[]
        description: The description of the information object
        displayName: Description

      shortName?:
        type: string
        description: A short technical name. (Avoid special characters not supported as variable names in common programming languages).
        displayName: Short name

      administrativeStatus:
        type: string
        description: Indicator for access to an item.
        displayName: Administrative status
        enum:
          - DRAFT
          - INTERNAL
          - OPEN
          - DEPRECATED

      createdDate:
        type: datetime
        description: The date on which the information object was created
        displayName: Created date

      versionRationale?:
        type: MultilingualText.MultilingualText[]
        description: The reason for making this version of the information object.
        displayName: Version rationale

      lastModified:
        type: datetime
        description: The date on which the object was last updated.
        displayName: Last modified date time

      lastModifiedBy?:
        type: string[]
        description: Last updated by
        displayName: Last updated by
        (Link.types): [ ContactInformation ]

      validFrom:
        type: datetime
        description: The date on which the information object is effective or valid. Set this date only once (constant). The same date for all versions of this information object.
        displayName: Valid from

      validUntil?:
        type: datetime
        description: The date on which the information object is no longer effective or valid.
        displayName: Valid until

      administrativeDetails?:
        type: AdministrativeDetails.AdministrativeDetails[]
        description: Administrative details (e.g. default language, documentation, localID, ...).
        displayName: Administrative details

      codes:
        type: ClassificationSubsetCode.ClassificationSubsetCode[]
        description: A list of references to classification items
        displayName: Codes